### ISSUE TITLE
Documentation link dead

### ISSUE THREAD

**Issue by zcraber** [beniza/keyboards#91]
The documentation link seems to be dead: https://sites.google.com/site/cibu/mozhi/mozhi2

**Comment by zcraber** [comment]
I've created a copy of the documentation here: https://mozhi-documentation.digitalmalayali.in/

**Comment by beniza** [comment]
Oh! I'm really sorry for not attending to this issue. I wasn't looking into
the issue page of my repo, hence missed this one. The issues for the
keyboard are tracked on the main Keyman repo. But I haven't
explicitly mentioned this on my fork. Maybe I should occasionally look in
there as well.

Thanks for reporting the issue. I'll fix it up.

/b

**Comment by zcraber** [comment]
Hope it was ok to copy the documentation to a new site. 
Is there a license for documentation like CC-BY? I couldn't find it in the original.

**Comment by beniza** [comment]
I think Cibu has moved/fixed the link... it's still active, somewhere on
his site. We just need to update the link in the documentation.... that's
it. I'm bit busy these days. So I'll do it during the Christmas break.
